refacto
ontoportal-lirmm/bioportal_web_ui pull request #148
Opened 2023-01-07 17:14 UTC by haddadzineddine

## Problem

When a new user has registered, they are not added to the mailing list.

## Solution

To add users to the mailing list, I utilized the sympa mailing service. Additionally, I developed a generic solution that allows you to easily switch to a different service with minimal modifications to the code.

## Changes Made

- Create a sympa mailer to add registered users to the mailing list.
- Create two routes: one for subscribing and one for unsubscribing.
- Add two buttons to the account page: one for subscribing and one for unsubscribing.

## Testing

To run tests, use the following command: `HOSTNAME=stageportal.lirmm.fr rspec spec/mailers`

## Types of changes

- [x] Bug fix

2023-01-09 08:39 UTC, syphax-bouazzouni requested changes
You added these two config variables $ANNOUNCE_LIST_SERVIC and $ANNOUNCE_SERVICE_HOST add it to the [bioportal_config_env.rb.sample](https://github.com/haddadzineddine/bioportal_web_ui/blob/fix/add-to-our-mailing-list/config/bioportal_config_env.rb.sample)

2023-01-13 14:23 UTC, syphax-bouazzouni requested changes
You did not fix this 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/29259906/212342227-609cef5e-32d3-4824-a280-bfcf44a1fd28.png">
make a  better UI for this

2023-01-18 09:02 UTC, syphax-bouazzouni requested changes

2023-01-18 09:02 UTC, syphax-bouazzouni commented on config/bioportal_config_env.rb.sample
> +# NOTE: You must use the REQUEST address for the mailing list. ONLY WORKS WITH MAILMAN LISTS.
```
# Announcements mailman mailing list REQUEST address, EX: list-request@lists.example.org
# NOTE: You must use the REQUEST address for the mailing list. ONLY WORKS WITH MAILMAN LISTS.
```
Why do you say `mailman` ?  In our case, we use `sympa`

2023-01-18 09:03 UTC, syphax-bouazzouni commented
@jonquet  can you test if this works, with our mailing list? I deployed it to Stageportal

2023-01-18 09:11 UTC, jonquet commented
@syphax-bouazzouni StagePortal has been setup with which parameters ?
$ANNOUNCE_LIST_SERVICE ||= "SERVICE_EXAMPLE"
$ANNOUNCE_SERVICE_HOST ||= "service@test.com"
$ANNOUNCE_LIST||= "users-list@test"  

I dont't see the changes in our private gite repo.

2023-01-18 09:13 UTC, syphax-bouazzouni commented
> @syphax-bouazzouni StagePortal has been setup with which parameters ? $ANNOUNCE_LIST_SERVICE ||= "SERVICE_EXAMPLE" $ANNOUNCE_SERVICE_HOST ||= "[service@test.com](mailto:service@test.com)" $ANNOUNCE_LIST||= "users-list@test"
> 
> I dont't see the changes in our private gite repo.

See https://gite.lirmm.fr/jonquetlab/bioportal-configs/-/commit/e5a89668c7d336cdbbfd030f35b0a5e7bb3b1a07

2023-01-18 09:37 UTC, jonquet commented
Ok. Thanks.  
- Creation of a new user (with all fieds filled) generates an error "Something went wrong" after clicking the Create button. 
- Unsuscription of an already existing user does not seems to work => I have unsuscribe my account jonquet@lirmm but double check its still on the mailing list. Maybe the mailing list is not setup to accept subscription/unsubscription by email (it might need somthing) I will check... in the meantime can we CC the support mailing list of the portal so we are sure the email was sent and the support people are informed. 

Quick comment on the flow and text messages : 

- You have un_subscribe successfully => You have successfully unsubscribed from our user mailing list: $ANNOUNCE_LIST|
- Before the button in the UI, put a sentence explaining what we are talking about.  Something like : "Subscribe to the *portalName* user mailing list : [BOUTON O/N] qui affiche l'état actuel de la subscription

<img width="270" alt="image" src="https://user-images.githubusercontent.com/7379183/213134054-f0eee6ec-6d93-467e-a9ab-437a29adde7c.png">

2023-01-18 13:36 UTC, haddadzineddine commented
TODO :

- [ ] test new user creation with annouce list enabled
- [ ]  send (un)subscribtion mail to our support mailing list in paralle
- [ ] update success subscribe message to add annouce list in the end
- [ ] update the ui , create button [ O/N ]

2023-01-20 07:12 UTC, syphax-bouazzouni commented
Hi @haddadzineddine , don't forget to write meaningful commit messages.
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/29259906/213637985-31ac7f53-2fca-44d9-b489-1fe3f7b8e043.png">

Do a rebase https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

2023-01-23 11:06 UTC, syphax-bouazzouni requested changes

2023-01-23 11:06 UTC, syphax-bouazzouni commented on app/views/users/show.html.haml
> +                  window.location.href = "/users/subscribe/" + "#{@user.username}"
Don't forget to protect  this two endpoints to be accessed only the owner and admins

2023-01-31 15:44 UTC, syphax-bouazzouni approved these changes

2023-01-31 15:46 UTC, merged