Feature: Extract chips component
ontoportal-lirmm/bioportal_web_ui pull request #181
Opened 2023-02-04 09:53 UTC by Bilelkihal

### Problem
We use the same code of check chips many times on the feedback page, and we gonna need it also on the browse page, so there gonna be a lot of repetitive code.

### Solution
I extracted the check chips as a reusable component that we can change the text of it.

### Screenshot
![chips check](https://user-images.githubusercontent.com/61744974/216760759-de06661f-6d35-4044-8fa3-02feface815f.png)

2023-02-07 07:56 UTC, syphax-bouazzouni approved these changes

2023-02-07 09:49 UTC, syphax-bouazzouni requested changes

2023-02-07 09:49 UTC, syphax-bouazzouni commented on app/assets/stylesheets/application.css.scss.erb
> +@import "chips";
Put in the 'component' style folder

2023-02-07 09:49 UTC, syphax-bouazzouni commented on app/components/chips_component.rb
> +    def initialize(text:)
text is not meaningful,  is it the value

2023-02-07 09:49 UTC, syphax-bouazzouni commented on app/components/chips_component.rb
> +    def initialize(text:)
I think that it would be better to have two arguments `name` and `value'. But the `name` will have a default value which is `text_underscore`

2023-02-16 09:23 UTC, syphax-bouazzouni requested changes

2023-02-16 09:37 UTC, Bilelkihal commented on app/views/home/feedback/feedback.html.haml
> +        = render(ChipsComponent.new(name:"bug", value: "Bug"))
I can't use this component in the feedback's branch cause it's not yet merged to developement

2023-02-16 13:28 UTC, syphax-bouazzouni commented on app/views/home/feedback/feedback.html.haml
> +        = render(ChipsComponent.new(name:"bug", value: "Bug"))
not an issue remove it from this PR, and import (merge) it in your feedback branch

2023-02-16 13:33 UTC, syphax-bouazzouni approved these changes

2023-02-16 13:54 UTC, merged