Include 'not available' text for missing preferred and preferred label values in the selected language.
ontoportal-lirmm/bioportal_web_ui pull request #231
Opened 2023-04-04 07:32 UTC by haddadzineddine

## Description
When selecting a specific language, it is possible that the `Preferred Name` and `prefLabel ` attributes may be empty. To inform the user that these attributes do not have a value in the selected language, we need to add feedback.

## Changes 
- [x] If `Preferred Name` empty add feeback.
- [ ] If `prefLabel Name` empty add feeback.

2023-04-05 17:21 UTC, syphax-bouazzouni commented
Can you add screenshots for this

2023-04-22 14:42 UTC, haddadzineddine commented
Use case :  [INRAE Thesaurus](http://[localhost:3000/ontologies/INRAETHES/?p=classes&conceptid=http%3A%2F%2Fopendata.inrae.fr%2FthesaurusINRAE%2Fc_21977](http://localhost:3000/ontologies/INRAETHES/?p=classes&conceptid=http%3A%2F%2Fopendata.inrae.fr%2FthesaurusINRAE%2Fc_21977))


![image](https://user-images.githubusercontent.com/35062242/233791163-8a9c5bb2-153a-478e-bccf-b4ef06ef2630.png)

2023-04-27 09:36 UTC, syphax-bouazzouni commented on app/views/concepts/_details.html.haml
> +          %td{nowrap: ""}= t('ontology_details.concept.synonyms')
Do the same for synonyms and definitions

2023-04-28 11:43 UTC, haddadzineddine commented
## Screenshots:


1. synonyms and definitions :
![image](https://user-images.githubusercontent.com/35062242/235138258-26fc055c-77fe-41e5-b83a-d91aadd991d4.png)

2. prefLabel : 
![image](https://user-images.githubusercontent.com/35062242/235138612-248ed869-a362-40bd-8a51-cee67d957baa.png)

3. Preferred name : 
![image](https://user-images.githubusercontent.com/35062242/235138856-d2e1f8e1-0da6-48e8-80bf-1c0a569d6fe5.png)

2023-05-03 07:41 UTC, syphax-bouazzouni requested changes
As discussed in our last meeting:

- Show the warning only if the preferred name is empty
- Do a better style and reuse the alert component

2023-05-04 08:58 UTC, syphax-bouazzouni commented
We will need a screenshot when done

2023-05-10 11:26 UTC, haddadzineddine commented
@Bilelkihal I need the alter component to close this PR.

2023-05-15 15:51 UTC, haddadzineddine commented
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/bc9e8e7b-232f-44e9-8cf9-603a14103b52)

2023-05-15 16:13 UTC, haddadzineddine commented
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/78a0df14-f722-474c-9a61-6c41f16ecc07)

2023-05-24 18:38 UTC, haddadzineddine commented
![Screenshot 2023-05-24 203356](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/fd559edb-31c7-4cb8-a67f-57978fedc812)

2023-05-25 12:21 UTC, syphax-bouazzouni commented
Added: 

- Add padding the concept details no prefLabel warning (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/231/commits/d9d463b995ced70b26da3b94b82c7e7804a7d44b)
- Make the concept details no prefLabel alert closable (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/231/commits/236d86f23c7486bba3477619eb07d11d49266702)
- In concepts treeview the ones with no prefLabel show only their id last part (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/231/commits/ae916ac23d7204e5e9bc65efc5c53653c84fca53)

2023-05-25 12:24 UTC, merged