Feature: Update summary page design
ontoportal-lirmm/bioportal_web_ui pull request #244
Opened 2023-05-12 13:14 UTC by hibadjebabria169

##  Context
## Changes 

- [integrate the new design of the summary page](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/4e6f1b82b9680a03497b4db688e7ba041d9719b9)
- [add summary pages assets to images/summary](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/56c392e82d5930f4acf5bff700197870366846aa)
- [add the css file associated to the summary page](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/8509242f36cd91b832d1f66d52f35e7e7e0dd4ce)
- [import summary scss file](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/a92b739823d831a2bf6a789c935e7a3efa42e712)
- [fetch all attributes in latest_submission in summary page](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/a02a1bfb63ae194c7f9140e423fc9726599867c4)
- [remove the poppins font-family in summary page](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/af46c0898bfd58582492c1afa629cf210d40b983)
- [se the css color variable --primary-color to summary page elements](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/c7dc93bcad9031d259ff86013104d154a08e89ba)
- [fix some paddings and width misalignmenets in summary page style](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/6f2b340021c341a8e4642456e0227aaccd30602f)
- [add the links section expanded var with its content](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/1c6d9bcf264afb1d72a97dda640f2a6eec302316)
- [add identifiers section expanded bar with its content](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/18a533e1f0e2f3e098bff3b1d17897a2e13e915a)
- [add persons and organizations section expanded bar with its content](https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/694bc25c13e705a4b36c310acd33df12367062b3)

2023-06-02 08:58 UTC, Bilelkihal commented
@syphax-bouazzouni 

This is the design for the tabs:

**HTML:**
```
  <div class="ontology-details-tabs">
      <div class="tab-items">
          <div class="active">
              Summary
              <hr>
          </div>
          <div>
              Concepts
              <hr>
          </div>
          <div>
              Properties
              <hr>
          </div>
          <div>
              Notes
              <hr>
          </div>
          <div>
              Mappings
              <hr>
          </div>
          <div>
              Schemes
              <hr>
          </div>
          <div>
              Collections
              <hr>
          </div>
          <div>
              Widgets
              <hr>
          </div>
      </div>
      <hr>
  </div>
```
**CSS**

```
.ontology-details-tabs{
    margin: 40px 0;
}
.ontology-details-tabs > hr{
    border: 1px solid #f3f3f3;
    width: 100%;
}
.ontology-details-tabs .tab-items{
    display: flex;
    margin: 0 50px;
}
.ontology-details-tabs .tab-items div{
    font-size: 16px;
    font-weight: 400;
    color: #5e5e5e;
    margin-right: 50px;
    cursor: pointer;
    opacity: 60%;
    transition: opacity 0.3s ease;
}

.ontology-details-tabs .tab-items div:hover{
 
    opacity: 100%;
}

.ontology-details-tabs .tab-items div hr{
    display: none;
    margin-top: 10px;
}
.ontology-details-tabs .tab-items .active{
    font-weight: 500;
    color: black;
    opacity: 100%;
}
.ontology-details-tabs .tab-items .active hr{
    display: block;
    border: 1px solid #43D112;
    opacity: 100%;
}
```

2023-07-05 10:51 UTC, syphax-bouazzouni requested changes
I marked all the changes that remain to do in the code.

@hibadjebabria169 please see and fix.

2023-07-05 10:51 UTC, syphax-bouazzouni commented on yarn-error.log
remove this file

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +        .summary-page-second-row
extract this section "depiction" to a helper or partial

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +            .depiction
use here an existent component

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +                  %img{src: asset_path("summary/info.svg")}/
implement the info component

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          - properties = {Creation_date: @submission_latest.creationDate, Modification_date: @submission_latest.modificationDate}
put this in the controller

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          - properties = {creators: @submission_latest.hasCreator, contributors: @submission_latest.hasContributor, curators: @submission_latest.curatedBy,
put this in the controller

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          - properties = {Is_Format_Of: @submission_latest.isFormatOf, Has_Format: @submission_latest.hasFormat,
put this in the controller

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          - properties = {known_Usage: @submission_latest.knownUsage, designed_For_Ontology_Task:@submission_latest.designedForOntologyTask,
put this in the controller

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          - properties = {Accrual_method: @submission_latest.accrualMethod, Accrual_periodicity: @submission_latest.accrualPeriodicity, Accrual_policy: @submission_latest.accrualPolicy,
put this in the controller

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +                %p Visits
extract this in a helper

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +              %div{data:{controller: 'metadata-downloader'}}
extract this in a partial or helper

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +                %header.pb-2.font-weight-bold= "Views of #{@ontology.acronym}"
extract this section into partial

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/metadata/_ontology_description_section.html.haml
> +  .creation_info
use component here

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_licenses.html.haml
> +    .creation_info
use component here

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/layouts/ontology_viewer/_header.html.haml
> +              - value = attribute_enforced_values('hasLicense')[sub.hasLicense] || sub.hasLicense
use componenent

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/layouts/ontology_viewer/_header.html.haml
> +      %a.mx-1.ontology-details-edit-button{href: "#{(@submission_latest || @ontology).id}?display=all", :target => '_blank'}
use component

2023-07-05 10:51 UTC, syphax-bouazzouni commented on app/views/layouts/ontology_viewer/_header.html.haml
> +        %a.mx-1.ontology-details-edit-button{href: edit_ontology_path(@ontology.acronym)}
use component

2023-07-06 09:28 UTC, hibadjebabria169 commented on app/assets/images/summary/logo.png
I couldn't delete this one, i'll double check

2023-07-06 09:33 UTC, hibadjebabria169 commented on yarn-error.log
![Capture d’écran du 2023-07-06 11-33-25](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/59914426/843c0fa8-dff0-46d0-89f8-31862012e66b)

2023-07-12 10:24 UTC, syphax-bouazzouni requested changes

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          = render DropdownContainerComponent.new(title: 'Dates', id: 'dates') do
extract this to a partial

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          = render DropdownContainerComponent.new(title: 'Links', id: 'link') do
extract this to a partial

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          = render DropdownContainerComponent.new(title: 'Methodology', id: 'methodology') do
extract this to a partial

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +                %button{:id => "getMetadataBackNquadsBtn", :class => "btn btn-primary", 'data-action': 'metadata-downloader#downloadNQuads'} N-Triple
make this button bigger and take all the spaces

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/metadata/_ontology_identifiers_section.html.haml
> +    .depiction
use components here

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/metadata/_ontology_projects_section.html.haml
> +%p.normal_text
use components here

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/metadata/_ontology_projects_section.html.haml
> +%p.normal_text
and extract an array of (label, values) as you did for the properties.

2023-07-12 10:24 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_metadata.html.haml
> +          = render DropdownContainerComponent.new(title: 'Persons and organizations', id: 'person_and_organization') do
extract to a partial this

2023-08-12 03:20 UTC, syphax-bouazzouni approved these changes

2023-08-28 11:45 UTC, merged