Feature/support multilingual part 2
ontoportal-lirmm/bioportal_web_ui pull request #252
Opened 2023-05-23 11:13 UTC by haddadzineddine

## Description

Modify the user interface to include support for displaying data in multiple languages.

## Screenshots
![Screenshot 2023-05-23 131050](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/21456754-0c54-4bdb-ad17-d489abbedec2)

## Changes made : 

- Refactor ontology_viewer_page_name to support multiple languages #3e1fde56
- Refactor sort_by in collection and schemes to support multiple languges #0b9282c6
- Update ontology_viewer title #fc4d801d
- Add all option in language selection #24ad1b31
- Show prefLabel with the specific language in case of all languages #52eed1f3

## Reviewers
@syphax-bouazzouni

2023-05-25 13:05 UTC, syphax-bouazzouni commented
Add to this PR, the display of the treeview depending on the selected language, like the mockup below 
<img width="693" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/0b94159b-9255-48cb-b427-75fc47958b79">

2023-06-01 20:13 UTC, haddadzineddine commented
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/b8ac32be-6665-40d2-8a74-559cb70bff4c)

2023-06-01 20:19 UTC, syphax-bouazzouni commented
> ![image](https://user-images.githubusercontent.com/35062242/242715578-b8ac32be-6665-40d2-8a74-559cb70bff4c.png)

Don't take always the first, do a selection by portal language preference. if the portal languages are  `:en`, and `:fr`, then show English first if found, else French otherwise show what you have randomly.

2023-06-07 09:39 UTC, syphax-bouazzouni requested changes
Don't work

<img width="2550" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/48402029-47b4-4018-8d75-c6139a54f508">

2023-06-08 14:26 UTC, haddadzineddine commented
![2](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/ce3ce570-b064-4f72-839d-2fc72bf390c8)

![Screenshot 2023-06-08 161159](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/c2db169e-e3a9-4329-83a6-d30e96eec144)

2023-06-30 08:28 UTC, haddadzineddine commented
@syphax-bouazzouni

2023-07-05 12:29 UTC, syphax-bouazzouni requested changes
I refactored some of the code and pointed out some changes to make.
@haddadzineddine  please test it again and see the changes requested.

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/helpers/application_helper.rb
> +      prefLabelLang, prefLabelHTML = get_concept_label(child.prefLabel)
extract a helper here

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/helpers/collections_helper.rb
> +    collections_labels.sort_by! do |s|
extract a re-usable helper here

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/helpers/ontologies_helper.rb
>      submission_lang = submission_languages(submission)
here handle the case, where submission_languages is empty.

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/helpers/ontologies_helper.rb
> -    current_lang = request_lang
here handle the case when request_lang is nil, select the portal language

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/helpers/schemes_helper.rb
> +      pref_label = s['prefLabel']
extract a re-usable helper (same as collection)

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/helpers/schemes_helper.rb
> +      pref_label = s['prefLabel']
duplicate with line 37

2023-07-05 12:29 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/properties.html.haml
> -      <table cellpadding="0" cellspacing="0" class="minimal concept_details" width="100%">
why this is removed ?

2023-09-04 02:12 UTC, syphax-bouazzouni commented on app/helpers/ontologies_helper.rb
> -    current_lang = request_lang
for now by default  portal language is set to "EN" in request_lang helper

2023-09-04 02:13 UTC, syphax-bouazzouni approved these changes

2023-09-04 02:13 UTC, merged