Feature: update upload ontology
ontoportal-lirmm/bioportal_web_ui pull request #292
Opened 2023-07-11 23:40 UTC by Bilelkihal

### Problem

### What did I do

### Screenshots

2023-07-12 23:01 UTC, syphax-bouazzouni requested changes

2023-07-12 23:01 UTC, syphax-bouazzouni commented on app/views/ontologies/_form.html.haml
> +        = render Form::SelectComponent.new(label: "Administrator", name: "ontology[administeredBy]", value: @user_select_list, selected: @ontology.administeredBy || session[:user].id, multiple: true,
here you removed two inputs that need to put again: 

-  Public or Private 
<img width="336" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/9b339b5a-5da0-411a-b8a2-672da42d3386">

- And when private give access to a list of users 
 
<img width="1371" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/dd0b1428-0ac8-401e-aab4-5ddc4dda1c17">

2023-07-12 23:01 UTC, syphax-bouazzouni commented on app/views/ontologies/_form.html.haml
> +        .outlined-circle.outlined-active-circle
do an array here of the 3 titles

2023-07-31 07:40 UTC, syphax-bouazzouni requested changes

2023-07-31 07:40 UTC, syphax-bouazzouni commented on app/assets/stylesheets/components/input_field.scss
> +.ts-control{
this is not related to this component

2023-07-31 07:40 UTC, syphax-bouazzouni commented on app/components/buttons/primary_button_component/primary_button_component.html.haml
> +- if @type == "submit"
create two components instead of a type variable

2023-07-31 07:40 UTC, syphax-bouazzouni commented on app/components/buttons/primary_button_component/primary_button_component.html.haml
> +.animation-container#loading-animation
extract this to a view component

2023-07-31 07:40 UTC, syphax-bouazzouni commented on app/components/buttons/primary_button_component/primary_button_component.html.haml
> +        console.log("working")
to remove

2023-07-31 07:40 UTC, syphax-bouazzouni commented on app/components/select_input_component/select_input_component.html.haml
> +    - is_selected_value = value == @selected
no need to have the variable `is_selected_value`

2023-07-31 07:40 UTC, syphax-bouazzouni commented on app/javascript/controllers/tom_select_controller.js
> +import { Controller } from "@hotwired/stimulus"
to remove this unused file

2023-07-31 08:19 UTC, Bilelkihal commented on app/components/select_input_component/select_input_component.html.haml
> +%select#upload-ontology-visibility{autocomplete:"off", multiple: @multiple ,data: {controller: "select-input", 'select-input':{'multiple-value':@multiple, 'open-add-value':@open_to_add_values}}}
I fixed it here: #310,
I'll merge this branch in this branch when u finish ur review on it.

2023-08-23 09:55 UTC, syphax-bouazzouni approved these changes

2023-08-24 07:05 UTC, merged