add search language selector
ontoportal-lirmm/bioportal_web_ui pull request #309
Opened 2023-07-28 13:40 UTC by haddadzineddine

2023-08-06 21:41 UTC, syphax-bouazzouni requested changes

2023-08-06 21:41 UTC, syphax-bouazzouni commented on app/views/layouts/_header.html.erb
> +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
don't import/use  bootstrap select

2023-08-06 21:41 UTC, syphax-bouazzouni commented on app/views/search/index.html.haml
> +          %select#select-beast(autocomplete="off" placeholder="Select a person...")
do a component

2023-08-06 21:41 UTC, syphax-bouazzouni commented on app/views/search/index.html.haml
> +
remove white this useless spaces

2023-08-06 21:41 UTC, syphax-bouazzouni commented on config/environments/development.rb
> -require "active_support/core_ext/integer/time"
don't change this file

2023-08-06 21:41 UTC, syphax-bouazzouni commented on package.json
> +    "bootstrap-select": "^1.13.18",
don't use bootstrap-select we already have tom-select

2023-08-10 14:18 UTC, haddadzineddine commented
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/35062242/050b7982-4079-4abd-acd1-8e3bcda1027a)

2023-08-10 14:20 UTC, syphax-bouazzouni commented on app/views/layouts/_header.html.erb
> +  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
remove this

2023-08-10 14:21 UTC, syphax-bouazzouni commented on app/views/search/index.html.haml
> +          %select#search_language.mb-4.w-25{autocomplete: "off",
use the component SelectInput

2023-08-10 14:22 UTC, syphax-bouazzouni commented on app/views/layouts/_header.html.erb
> +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.9.2/css/flag-icons.min.css"/>
import in application.scss.css

2023-08-10 14:23 UTC, syphax-bouazzouni commented on app/components/select_input_component/select_input_component_controller.js
> +        } else {
don't do if else

2023-09-05 00:58 UTC, syphax-bouazzouni approved these changes

2023-09-05 00:59 UTC, merged