Remove handlebars dependecy and update ontology properties tab to use plain HTML
ontoportal-lirmm/bioportal_web_ui pull request #346
Opened 2023-09-20 11:59 UTC by SirineMhedhbi

2023-10-03 08:56 UTC, syphax-bouazzouni commented
There is a bug when you go to https://testportal.lirmm.fr/ontologies/INRAETHES/?p=properties it does not select by default the first one, so the page is blank
<img width="1413" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/feceb19b-c26e-4908-8e2d-d3a6b0b45b73">

2023-10-03 09:03 UTC, syphax-bouazzouni requested changes

2023-10-03 09:03 UTC, syphax-bouazzouni commented on app/views/ontologies/_tab_properties.html.haml
you should put this file in the properties folder, and make the show action of the PropertiesController

2023-10-03 09:03 UTC, syphax-bouazzouni commented on config/routes.rb
> +  get '/tab_properties', to: 'ontologies#tab_properties'
make it use properties#show action instead

2023-10-03 09:03 UTC, syphax-bouazzouni commented on app/controllers/ontologies_controller.rb
> +  def tab_properties
put this instead in properties_controller as a `show` action

2023-10-03 09:31 UTC, syphax-bouazzouni commented
Another bug is when you click on some properties it does not work 

for example `member` in https://testportal.lirmm.fr/ontologies/INRAETHES/?p=properties

in you don't show a loader when clicking on a property

2023-10-03 19:23 UTC, SirineMhedhbi commented on app/views/ontologies/_tab_properties.html.haml
There is no properties file or properties controller in the project

2023-10-03 19:39 UTC, syphax-bouazzouni commented on app/views/ontologies/_tab_properties.html.haml
add a properties controller then

2023-10-04 11:37 UTC, SirineMhedhbi commented
@syphax-bouazzouni  Fixed 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/ac4903a4-626c-4d9c-82ed-d8d59feb63e4)

2023-11-13 15:27 UTC, syphax-bouazzouni approved these changes
Approved, but it can be optimized someday. By doing: 
* A component for the property  tree view 
* And don't fetch all the properties for the ontologies#properties action.

2023-11-15 11:32 UTC, merged

2023-11-15 11:32 UTC, syphax-bouazzouni commented
Good bye handlebars 👋