Fix changes summary page
ontoportal-lirmm/bioportal_web_ui pull request #364
Opened 2023-10-27 08:07 UTC by SirineMhedhbi

2023-10-30 15:51 UTC, syphax-bouazzouni commented
@syphax-bouazzouni check the remaining changes in the https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit,  depending of the back

2023-11-02 07:05 UTC, syphax-bouazzouni requested changes
Hi @SirineMhedhbi,

I'm not a big fan of this dots 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/5dafd230-4cca-4f52-bc05-3eec3db4747f)

Change it to just pragraphs, and with less margin buttom

2023-11-02 08:15 UTC, SirineMhedhbi commented
@syphax-bouazzouni  okay i will change it

2023-11-03 07:30 UTC, syphax-bouazzouni approved these changes

2023-11-03 09:40 UTC, merged