Feature: Add back button in upload ontology form
ontoportal-lirmm/bioportal_web_ui pull request #397
Opened 2023-12-05 14:45 UTC by Bilelkihal

Done in this PR:
I added a button to exit the upload ontology form
![Capture d'écran 2023-12-05 154304](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/62e23704-1ec7-4f84-91a3-36b6bf8f37ab)

2023-12-06 13:01 UTC, syphax-bouazzouni approved these changes

2023-12-06 13:02 UTC, syphax-bouazzouni requested changes
You need to put again the ".Upload-ontology-title" css class or update the test

2023-12-07 10:26 UTC, Bilelkihal commented on app/views/ontologies/new.html.haml
> -            .Upload-ontology-title
Done

2023-12-07 13:35 UTC, syphax-bouazzouni approved these changes

2023-12-07 13:36 UTC, merged