Feature: Add agent tooltip in summary page
ontoportal-lirmm/bioportal_web_ui pull request #404
Opened 2023-12-07 09:50 UTC by Bilelkihal

### Done in this PR:
I added a tooltip when we hover an agent in people and organizations bloc in summary page,
The information I'm displaying is: **Type (using an icon)**, **name**, **email**, **identifiers** and **affiliations** of the agent.
there are two types of agents:
- person:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/918b19bc-bb29-4914-812b-4257adfb02af)

- Organization:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/6040058a-eb55-48d3-abb3-04669f51603d)

** Also I added an icon to indicate the type of the agent in the agent chip

Ps. there are some agents have no type (only name and email) and they are considered as persons.

2023-12-07 12:29 UTC, syphax-bouazzouni requested changes
See requested changes in the code,
and for the UI, make it more smaller, as the marckup bellow 
<img width="386" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/525c6830-8f81-44b7-aae3-b10b98e872e4">

2023-12-07 13:54 UTC, Bilelkihal commented on app/assets/images/icons/person.svg
People icon is different:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/0a2a41ca-5042-4107-875f-f24e4b21683e)

2023-12-07 14:02 UTC, syphax-bouazzouni requested changes

2023-12-07 14:09 UTC, syphax-bouazzouni requested changes
Can you also update the chips content to be like this 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/c8b9061b-cf55-40e3-a1a7-dfe73e37f92b)

2023-12-14 10:38 UTC, syphax-bouazzouni requested changes
I need the fix of word breaking and remove the scroll before merging this

2023-12-14 13:57 UTC, Bilelkihal commented
@syphax-bouazzouni 
I removed the scroll indicators, now for the text overflow we do text-truncate, 
Concerning the word break I saw the license PR and the change I did was just for the license badge.

2023-12-15 04:55 UTC, merged