Feature: Update search page design
ontoportal-lirmm/bioportal_web_ui pull request #412
Opened 2023-12-18 10:29 UTC by Bilelkihal

## Problem:
1- This page’s logic is written in a javascript file of 1053 lines of code:
- This makes this code extremely hard for modification and extention
- We make the HTML elements directly in Javascript which is not a good practice
- It’s based on JQuerry

2- The page has an old UI

## Done in this PR:
- A modern UI 
- Migrate JQuerry code to a ruby code in search controller

## Screenshots:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/86bfc9b0-01d8-4633-ac9b-f70381c294c2)
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/2ad96d1d-371d-44be-8430-a52f2bbff2ad)

2023-12-18 10:48 UTC, syphax-bouazzouni requested changes
Some details to change, see comments.
And you need to remove the old JS code with this PR

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/assets/images/icons/visualize.svg
Don't add icons, without checking before if we don't have one. in this there is `eye.svg` i think 

Managing icons is hard, so add new ones only if necessary.

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/assets/images/icons/search.svg
Already existent, loop.svg

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/assets/images/icons/arrow-down.svg
Already existent

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component_controller.js
there is already controller that do that, called "reveal"

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/javascript/controllers/index.js
> +application.register("form-display", FormDisplayController)
don't change this

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +                    = "#{@mappings} mapped ontologies"
use the term, "reuse", as decided by clement in the last meeting.

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +                        - #result.update(is_sub_component: true)
remove this line

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/javascript/controllers/search_controller.js
> +import { Controller } from "@hotwired/stimulus"
why there are two new controllers?  that do relative the same thing (show/hide blocks)

2023-12-18 10:48 UTC, syphax-bouazzouni commented on app/javascript/controllers/search_controller.js
> +    this.hideOptionsButtonTarget.classList.remove('d-none')
use `toggle` which add class if no existent or remove otherwise

2023-12-18 10:57 UTC, Bilelkihal commented
@syphax-bouazzouni 
I'm not sure if the old js code is used only for this page, isn't it used for the jump_to feature?

2023-12-18 10:59 UTC, syphax-bouazzouni commented
> @syphax-bouazzouni I'm not sure if the old js code is used only for this page, isn't it used for the jump_to feature?

If this case, also update the jump_to to not use it

2023-12-20 15:34 UTC, syphax-bouazzouni requested changes

2023-12-20 15:34 UTC, syphax-bouazzouni commented on config/initializers/bugsnag.rb
> +  config.api_key = "00ccc6304835fbd8f08f6764a6611704"
this need to be private and not pushed

2023-12-20 15:34 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +      @no_results = @search_results.eql?([])
can be replaced with ` @search_results.empty?`

2023-12-20 15:34 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +  def group_results_by_ontology(results)
if you don't re-use this function in multiple places, just write it in where used

2023-12-20 15:34 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +      element_id = grouped_results[key][0].id
extract vaibel `grouped_results[key].first`, instead of calling ` grouped_results[key][0]`each time

2023-12-20 15:34 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +      end_point = get_after_last_slash(ui_link)
just do `ui_link.split('/').last` instead of creating a function

2023-12-20 15:34 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +    unless definitions_array.eql?(nil)
replace with `definitions_array.nil?`

2023-12-20 15:34 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +      definitions_array.each do |defintion|
replace  all this function with ` Array(definitions_array).join(' ')`

2023-12-24 21:42 UTC, syphax-bouazzouni requested changes
I have done the following:
* Fixed the rebase of this branch to development  (to have only the commits of this PR)
* Fixed bugsnag gem configuration and removed the published public API KEY (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/412/commits/4060e0baac45ee2922afbf592e8f98bf6b888438)
* Simplified search result component arguments  by inferring some from the others and removing the unused (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/412/commits/f12ce21ba9aa4ae837a916ee3e8306134129b855)
* Simplified the search parameters key naming to avoid duplication, by using the same naming in the UI and those sent to API (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/412/commits/4b9a9c1c4635f9e1822ae940d4551276dcabc8ec)
* Went back to `bp_search.js` the file and strictly converted all the functions to search_aggregator.rb file used in search_controller.rb (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/412/commits/d3bc6b2e9bfeaa88871836b28d3a8f4682c336c4)

See the comments to know what is remaining to do  @Bilelkihal

2023-12-24 21:42 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +        =  link_to_modal(nil, "/ajax/class_details?modal=true&ontology=#{@ontology_acronym}&conceptid=#{@uri}&styled=false",data: { show_modal_title_value: @title, show_modal_size_value: 'modal-xl' }
extract a function for this block

2023-12-24 21:42 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +        =  link_to_modal(nil, "/ajax/biomixer/?ontology=#{@ontology_acronym}&conceptid=#{@uri}",data: { show_modal_title_value: @title, show_modal_size_value: 'modal-xl' }) do
extract a function for this block

2023-12-24 21:42 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +            .button.icon-right{'data-action': "click->search-result-component#showReuses"}
extract a function  or a new button component for this block

2023-12-24 21:42 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +            .button.icon-right{'data-action': "click->search-result-component#showSubOntologies"}
extract a function or a new button component for this block

2023-12-24 21:42 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component.html.haml
> +.search-result-component{class: sub_component_class, 'data-controller': 'search-result-component'}
use existent `reveal` stimulus controller, and extend it if needed

2023-12-24 21:42 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component_controller.js
> +import { Controller } from "@hotwired/stimulus";
extend `reveal` stimulus controller to do this

2023-12-24 21:42 UTC, syphax-bouazzouni commented on config/bioportal_config_env.rb.sample
> +$BUGSNAG_APIKEY
update to `$BUGSNAG_APIKEY= <you api>`

2023-12-26 13:30 UTC, syphax-bouazzouni requested changes

2023-12-26 13:30 UTC, syphax-bouazzouni commented on app/views/search/index.html.haml
> -                = t("search.categories")
you should remove this from locals file also

2024-01-03 08:34 UTC, syphax-bouazzouni requested changes
See comments to find the requested changes

2024-01-04 11:05 UTC, syphax-bouazzouni requested changes

2024-01-04 11:05 UTC, syphax-bouazzouni commented on app/controllers/home_controller.rb
> +  def annotator_recommender_form
you can remove this it is duplicated

2024-01-04 11:05 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component_controller.js
Still same remark here: Stimulus controllers must be generic and reusable.

2024-01-04 11:05 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component_controller.js
If you can't make work with with the already existent `reveal` , create a new, but it need to be generic, just stimulus controller that open and close block if we click on a button.

2024-01-04 11:05 UTC, syphax-bouazzouni commented on app/components/display/search_result_component/search_result_component_controller.js
Something like this https://getbootstrap.com/docs/4.3/components/collapse/#multiple-targets, but without  using bootstrap as we may remove it one day

2024-01-05 14:01 UTC, merged

2024-01-25 22:38 UTC, jonquet commented
Missing "e" at the end of obsolete on the button. 
Maybe we can add "advanced" from the message "Show advanced options" and "Hide advanced options"  ... these options are just options not realy advanced options.

2024-01-25 22:39 UTC, jonquet commented
I would put the little reuse icon in green and iractly in the button 
<img width="33" alt="Capture d’écran 2024-01-25 à 23 38 54" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/9905420e-83f4-4fe4-8b65-5dc38a63e7be">

and then remove the sentence and the icon from top of the reuse section: 
<img width="314" alt="Capture d’écran 2024-01-25 à 23 39 22" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/71a67940-01ec-4d02-a18e-a3dfdedcc85d">

2024-01-25 22:48 UTC, jonquet commented
When using the "Adavanced options" panel ... we look for the search button under the options rather than on the "magnifying glass" icon on the upper right corner

2024-01-25 22:49 UTC, jonquet commented
When searching and getting a term with mutliple definitons appended: 
https://stageportal.lirmm.fr/search?q=leaf+area+index&lang=all&ontologies_list%5B%5D=MEAT-T
Can we at leas detect the appendment and separate the values with a newline/new paragrhah ?