Fix: home page issues
ontoportal-lirmm/bioportal_web_ui pull request #417
Opened 2023-12-20 13:48 UTC by Bilelkihal

### Done in this PR:
- Combine support and collaborations sections in one section.
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/5fbe6249-406f-41dc-9f2f-59f3ee51564c)
The new config variable:
```
$HOME_PAGE_LOGOS = [
    {
      img_src: 'logos/supports/numev.png',
      url: 'http://www.lirmm.fr/numev',
      target: '_blank'
    },
    {
      img_src: 'logos/supports/anr.png',
      url: 'https://anr.fr/en',
      target: '_blank'
    },
    {
      img_src: 'logos/supports/eu.png',
      url: 'https://commission.europa.eu/research-and-innovation_en',
      target: '_blank'
    },
    {
      img_src: 'logos/collaboration/d2kab.png',
      url: 'http://d2kab.mystrikingly.com',
      target: '_blank'
    },
    {
      img_src: 'logos/collaboration/lirmm.png',
      url: 'http://www.lirmm.fr',
      target: '_blank'
    },
    {
      img_src: 'logos/collaboration/inrae.png',
      url: 'https://www.inrae.fr/enm',
      target: '_blank'
    },
    {
      img_src: 'logos/collaboration/stanford.png',
      url: 'https://www.stanford.edu',
      target: '_blank'
    }
    
]

```

- Add discover ontologies button on home page.
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/4bdae38d-053b-4e55-903d-a1b802f615df)

- Make Recommender and Annotator height smaller, and add a button to insert a sample text
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/68d63567-6397-4446-9f51-5e77ce56b7d4)

- Fix home page hardcoded colors.
- ...

2023-12-20 15:38 UTC, syphax-bouazzouni requested changes

2023-12-20 15:38 UTC, syphax-bouazzouni commented on app/helpers/metadata_helper.rb
> -      display_contact([value]).html_safe
you need to not change this

2023-12-20 15:38 UTC, syphax-bouazzouni commented on app/views/home/index.html.haml
> +    recommenderAnnotatorArea.value = 'Melanoma is a malignant tumor of melanocytes found mainly in the skin but also in the intestine and the eye.';
this needs to be in the local files, in English and French

2023-12-20 15:38 UTC, syphax-bouazzouni commented on app/views/ontologies/sections/_additional_metadata.html.haml
> +  - sub_hash = @submission_latest.to_hash.except(:context, :links, :ontology)
this file need to be unchanged

2023-12-20 15:38 UTC, syphax-bouazzouni commented on config/initializers/bugsnag.rb
> +  config.api_key = "00ccc6304835fbd8f08f6764a6611704"
this file is private

2024-01-09 15:54 UTC, syphax-bouazzouni requested changes

2024-01-09 15:54 UTC, syphax-bouazzouni commented on app/views/home/index.html.haml
> +        = render Buttons::RegularButtonComponent.new(id: 'discover-ontologies-button', value: t('home.discover_ontologies_button'), variant: "secondary", state: "regular", href: "/ontologies") do |bt
add a helper for this, as you did for `upload_ontology_button`, otherwise, it is some how hard to read

2024-01-09 15:54 UTC, syphax-bouazzouni commented on app/views/home/index.html.haml
> +          .insert-sample-text-button{onclick: "insertSampleText('#{t('sample_text')}')"}
you can extract this into a stimulus controller, as you will re-use in multiple pages (annotator, recommended and homepage)

2024-01-11 15:08 UTC, syphax-bouazzouni approved these changes
Approved, good work.
But before I can merge it I need you to update our configuration files, in the `ontoportal_configs` private repository

2024-01-12 14:35 UTC, merged

2024-01-25 22:56 UTC, jonquet commented
With the addition of the OntoPortal logo, it does not fit in one line anymore... 
<img width="944" alt="Capture d’écran 2024-01-25 à 23 56 00" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/392c9d3d-8a45-4b26-aba7-98820720ade3">