Fix the display of obsolete class in concept section
ontoportal-lirmm/bioportal_web_ui pull request #419
Opened 2023-12-21 13:56 UTC by SirineMhedhbi

2024-01-02 03:31 UTC, syphax-bouazzouni requested changes

2024-01-02 03:31 UTC, syphax-bouazzouni commented on app/helpers/application_helper.rb
> +        pref_label_html = "<span class='obsolete_class'>#{child.prefLabel}</span>"
why is there no `select_language_label`, here?

2024-01-08 08:31 UTC, syphax-bouazzouni approved these changes

2024-01-08 08:42 UTC, merged

2024-01-25 22:54 UTC, jonquet commented
OK for release in v2.7.3