Feature: Add icons to display orcid, and affiliations in agent tooltip
ontoportal-lirmm/bioportal_web_ui pull request #420
Opened 2023-12-21 14:26 UTC by Bilelkihal

### Done in this PR:
- Add icons to display orcid, and affiliations in agent tooltip
(in case the orcid is a URL, I convert it into a number)
![agent tooltip](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/948cd797-766d-410b-bc55-6ee2121d5756)

2023-12-28 23:14 UTC, syphax-bouazzouni requested changes

2023-12-28 23:14 UTC, syphax-bouazzouni commented on app/helpers/agent_helper.rb
> +            inline_svg_tag('icons/orcid.svg', class: 'agent-dependency-icon') +
for agents of type "Organization" they don't use ORCID but a ROR, so in this case the Icon need to be this one 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/9a3c1aa8-5073-4e85-86fc-3840fd4e91a9)
or something like it.
this there website https://ror.org/

2024-01-02 19:02 UTC, syphax-bouazzouni approved these changes

2024-01-02 19:02 UTC, merged

2024-01-25 22:25 UTC, jonquet commented
@Bilelkihal We would need also to revise the Organization tooltip and display  in the UI the acronym of the organization (if present, the name if absent) and in the popup on mouse over, the name of the organisation with the acronyme between parenthesis right after.
<img width="601" alt="Capture d’écran 2024-01-25 à 23 23 46" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/b42f8065-ad64-441c-bfd8-561dcf287381">

2024-01-25 22:27 UTC, jonquet commented
Also based on recent discussion, the person tooltip should not display the email. ... to be verified.