Feature : internationalization part 1
ontoportal-lirmm/bioportal_web_ui pull request #472
Opened 2024-01-29 13:08 UTC by SirineMhedhbi

2024-01-29 13:26 UTC, syphax-bouazzouni requested changes
Seems there is an issue in the yaml file and don't pass the tests 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/f05f3153-2c16-452a-ac1e-ea8447b72f54)

2024-01-29 17:17 UTC, syphax-bouazzouni requested changes

2024-01-29 17:17 UTC, syphax-bouazzouni commented on config/locales/en.yml
> +    submit_new_ontology: Submit New Ontology
this need to be `Submit new ontology` not `Submit New Ontology` to pass the system tests

2024-02-05 08:56 UTC, Bilelkihal requested changes

2024-02-05 08:56 UTC, Bilelkihal commented on app/views/home/feedback/feedback.html.haml
> +          %font.register-optional= t("home.feedback.optional")
For '(optional)' it's better to keep the parentheses in the UI, so we keep the local lang files clean with only texts,
Like this for example:
`"(#{t('home.feedback.optional')})"`

2024-02-05 08:56 UTC, Bilelkihal commented on app/views/home/feedback/feedback.html.haml
> +        %font.register-optional= t("home.feedback.optional")
Same as above

2024-02-05 08:56 UTC, Bilelkihal commented on app/views/home/feedback/feedback.html.haml
> +        %font.register-optional= t("home.feedback.optional")
Same as above

2024-02-05 08:56 UTC, Bilelkihal commented on app/views/home/index.html.haml
> +              = t('home.insert_sample_text')
insert_sample_text already exists in annotator and recommender, 
replace this with:
= t('insert_sample_text')

2024-02-05 08:56 UTC, Bilelkihal commented on app/views/home/index.html.haml
>          = link_to 'See details','/statistics', target: "_blank"
You forgot this 'See details' text

2024-02-05 14:10 UTC, Bilelkihal reviewed
Great work

2024-02-05 14:14 UTC, merged