Feature: improve search input component
ontoportal-lirmm/bioportal_web_ui pull request #499
Opened 2024-02-09 10:58 UTC by Bilelkihal

### Done in this PR:

### Demo
[Capture vidéo du 09-02-2024 11:52:55.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/f69757eb-1cde-4aeb-8b04-ae6928519bd3)

2024-02-27 18:07 UTC, syphax-bouazzouni requested changes
The icon seems to not be well positioned  
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/0250f530-5850-44c1-a335-5a1253fe59ba)
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/706578c1-71a4-4519-af01-74afee222dbe)


Also  add the loading state, watch a request is sent in the place of the icon, a loader need to be shown.

2024-02-28 15:19 UTC, syphax-bouazzouni requested changes
Need to implement the laoding state before been merged 
and also pass tests

2024-03-07 22:50 UTC, Bilelkihal commented
This is the loader (I puted a debugger in the js just to see it clearly cause in this example on the home page it's so fast to be seen):
[Capture vidéo du 07-03-2024 23:46:21.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/374c4424-b691-47e4-8fab-866090aa156d)

2024-03-12 11:34 UTC, syphax-bouazzouni requested changes

2024-03-12 11:34 UTC, syphax-bouazzouni commented on app/components/search_input_component/search_input_component_controller.js
> +            this.buttonTarget.href = `/search?q=${inputValue}`;
this value can't be hardcoded, otherwise, we can't reuse this component.

2024-03-12 22:45 UTC, Bilelkihal commented
@syphax-bouazzouni in case there's nothing else to do with this PR, merge it to your indexing PR and I'll fix the text overflow problem

2024-03-13 09:18 UTC, syphax-bouazzouni requested changes

2024-03-13 09:18 UTC, syphax-bouazzouni commented on app/components/search_input_component/search_input_component.html.haml
> +  'data-search-input-button-url-value': '/search?q='
this need to be a variable as `@ajax_url`

2024-03-15 12:02 UTC, syphax-bouazzouni approved these changes

2024-03-15 12:29 UTC, merged