Adding Content Finder Page
ontoportal-lirmm/bioportal_web_ui pull request #511
Opened 2024-02-22 15:02 UTC by imadbourouche

### Content Finder Page
- Adding content finder page to be able to request a resource from a graph and diplay it with different format
- Supported formats:
  - JSON.
  - XML.
  - NTRIPLES
  - TURTLE

### Demo
[demo_content_finder.webm](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/66650181/eac9ee10-95c1-46f9-aa56-d7dbe7cc8223)

2024-02-22 15:06 UTC, syphax-bouazzouni approved these changes

2024-02-22 15:10 UTC, SirineMhedhbi commented
good job Imad 👌

2024-03-27 20:31 UTC, syphax-bouazzouni requested changes
Seems to  not work

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/569a9242-5d45-4924-99b6-2f9d94cb1810)

2024-03-27 20:31 UTC, syphax-bouazzouni commented on app/controllers/content_finder_controller.rb
> +            http = Net::HTTP.new(url.host, url.port)
use Faraday instead of Net::HTTP (ask chatgpt to convert)

2024-03-27 20:31 UTC, syphax-bouazzouni commented on app/javascript/controllers/content_finder_controller.js
> +    result: String,
don't pass the content to display in the `result` value, just do `this.element.textContent` and pass the result in the HTML element content. 
Bellow an example 

```html
<div controller="content-finder">
#{@result}
</div>
```

2024-04-03 11:51 UTC, syphax-bouazzouni requested changes
Need to add the HTML converter

2024-04-05 06:38 UTC, syphax-bouazzouni approved these changes

2024-04-07 09:55 UTC, merged