Fix: Harmonize API and UI urls in Search, Annotator and Recommender pages
ontoportal-lirmm/bioportal_web_ui pull request #534
Opened 2024-03-12 11:37 UTC by Bilelkihal

### Context
Current URLs of the search, Annotator and Recommender services, show the lists of params in this way:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/559a1ae1-43eb-4e18-a9ce-97b03c66fcd3)

But the api url shows:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/67645639-b51e-4e3f-9c28-f894bcc3d7c3)

2024-03-12 12:13 UTC, syphax-bouazzouni requested changes
Renaming `ontologies_list` to `ontologies` was not enaugh ? why all this added complexity

2024-03-12 12:52 UTC, syphax-bouazzouni commented
> Renaming `ontologies_list[] ` by `ontologies[]` will result by a url like this: _**ontologies**%5B%5D=SOIL&**ontologies**%5B%5D=AGFOOD._ and if I remove the '[]' then it will concider it as a single value and take only one value.

why you don't remove the `[]` from you select component input ?

2024-03-12 13:34 UTC, Bilelkihal commented
> > Renaming `ontologies_list[] ` by `ontologies[]` will result by a url like this: _**ontologies**%5B%5D=SOIL&**ontologies**%5B%5D=AGFOOD._ and if I remove the '[]' then it will concider it as a single value and take only one value.
> 
> why you don't remove the `[]` from your select component input and pass a single string with comma as value?

The default behavior of the select component is to return an array of values we can't achieve that without handling this in the js

2024-03-18 08:38 UTC, syphax-bouazzouni approved these changes

2024-03-18 08:42 UTC, merged