Feature: Federate browse page
ontoportal-lirmm/bioportal_web_ui pull request #621
Opened 2024-05-09 15:22 UTC by syphax-bouazzouni

### Context
See https://github.com/ontoportal/ontoportal-project/issues/38

### Changes 
* Show in the browse ontologies from external portals 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/aa02206a-0061-4fda-87ec-381c6d8ccd7f)

* Have custom styles depending on the origin ontology 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/ad0c3a95-f5c3-4844-a066-13b5cf3865a9)

* Redirect to the external portal for federated ontologies 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/4243fe16-5329-408e-8643-b75de1fe7d8c)

* Federate filters  (categories, groups, languages, status, format, search) and sort by.

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/cb269482-fdc7-405a-ba86-92b6110d22e7)

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/16aff13f-59ad-4b0a-9ac9-8ce7c923b22d)

* Add configuration samples 
```ruby
# Federation configuration
$FEDERATED_PORTALS = {
  bioportal: {
    name: "BioPortal",
    api: 'https://data.bioontology.org/',
    ui: 'https://bioportal.bioontology.org/',
    apikey: '8b5b7825-538d-40e0-9e9e-5ab9274a9aeb',
    color: '#234979',
    'light-color': '#E9F2FA',
  },
  agroportal: {
    name: "AgroPortal",
    api: 'https://data.agroportal.lirmm.fr',
    ui: 'https://agroportal.lirmm.fr',
    apikey: '1de0a270-29c5-4dda-b043-7c3580628cd5',
    color: '#349696',
    'light-color': '#F1F6FA',
  },
  ecoportal: {
    name: "EcoPortal",
    api: 'https://data.ecoportal.lifewatch.eu/',
    ui: 'https://ecoportal.lifewatch.eu',
    apikey: "43a437ba-a437-4bf0-affd-ab520e584719",
    color: '#2076C9',
    'light-color': '#E9F2FA',
  },
  # earthportal: {
     name: 'EarthPortal',
     api: 'https://earthportal.eu:8443/',
     ui: 'https://earthportal.eu',
     apikey: "c9147279-954f-41bd-b068-da9b0c441288",
      color: '#404696',
      'light-color': '#404696'
   },
  biodivportal: {
    name: "BioDivPortal",
    api: 'https://data.biodivportal.gfbio.org/',
    ui: 'https://biodivportal.gfbio.org/',
    apikey: "47a57aa3-7b54-4f34-b695-dbb5f5b7363e",
    color: '#349696',
    'light-color': '#EBF5F5',
  }
}
```

2024-05-09 18:26 UTC, syphax-bouazzouni commented on app/controllers/application_controller.rb
> +      slices_acronyms = slices.map {|s| s.acronym} rescue binding.pry
to remove

2024-05-09 18:28 UTC, syphax-bouazzouni commented on config/initializers/ontologies_api_client.rb
> +  config.federated_portals = $FEDERATED_PORTALS || []
change to `$FEDERATED_PORTALS || {}`

2024-05-09 19:05 UTC, Bilelkihal requested changes

2024-05-09 19:05 UTC, Bilelkihal commented on app/components/ontology_browse_card_component/ontology_browse_card_component.html.haml
> +              = render Display::InfoTooltipComponent.new(text: "Federated ontology from #{onto_link}", icon: 'external-link.svg')
I don't really like this 'Federated' word, I don't think the regular user will understand what that is (To be discussed in Rome)

2024-05-09 19:05 UTC, Bilelkihal commented on app/controllers/concerns/submission_filter.rb
> +    submissions = submissions.map { |x| [x[:ontology][:id], x] }.to_h rescue binding.pry
To be deleted also

2024-05-09 20:04 UTC, syphax-bouazzouni commented on app/components/ontology_browse_card_component/ontology_browse_card_component.html.haml
> +            - if external_ontology?
can't do that easily, as there is no way to change its color, without creating a custom `css` for each portal.

2024-05-10 16:55 UTC, syphax-bouazzouni commented
Deployed in https://testportal.lirmm.fr/ontologies

2024-09-11 13:11 UTC, merged