Fix: Redirect to the login page when accessing private ontology while being not authenticated.
ontoportal-lirmm/bioportal_web_ui pull request #673
Opened 2024-06-13 09:48 UTC by Bilelkihal

### Changes
- Redirect the user to the login page when trying to access a private ontology while being not logged in.
- Use alert component for login errors to display them better.
- Add a message in the login page to say, this is a private ontology please login when trying to access a private ontology while being not logged in.

### Demo
https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/7fe1678f-4d92-446a-b485-cd11e7a153c5

2024-06-13 09:51 UTC, Bilelkihal commented
@syphax-bouazzouni I started this branch from the stage branch (so I can launch the dev env) you can see that the commits history is divergent than the one of of the development, to review this PR, just see the last three commits or these five files:
`app/controllers/ontologies_controller.rb`
`app/views/login/index.html.haml`
`app/controllers/login_controller.rb`
`config/locales/en.yml`
`config/locales/fr.yml`

2024-06-13 09:56 UTC, Bilelkihal reviewed
do a merge for the development branch here once the changes are approved

2024-06-13 13:22 UTC, jonquet commented
Top! perfect.

2024-06-21 08:46 UTC, syphax-bouazzouni requested changes

2024-06-21 08:46 UTC, syphax-bouazzouni commented on app/helpers/check_resolvability_helper.rb
> +    5000
remove this change

2024-06-21 08:46 UTC, syphax-bouazzouni commented on Gemfile.lock
> -  x86_64-linux-gnu
remove this change

2024-06-21 08:46 UTC, syphax-bouazzouni commented on app/views/mappings/mappings_ontologies_table.html.haml
> += render TurboFrameComponent.new(id: 'mappings_table') do
this file is to remove

2024-06-21 08:46 UTC, syphax-bouazzouni commented on app/controllers/ontologies_controller.rb
> +        redirect_to "/login?redirect=/ontologies/#{params[:ontology]}&notices=#{escape(t('login.private_ontology'))}"
```ruby 
redirect_to "/login?redirect=/ontologies/#{params[:ontology]}&notices=#{escape(t('login.private_ontology'))}", notice: "yourt message"
```

2024-06-21 08:46 UTC, syphax-bouazzouni commented on app/controllers/login_controller.rb
> +    @notices = [params[:notices]] if params[:notices]
not needed if your use rails notices

2024-06-21 08:46 UTC, syphax-bouazzouni commented on app/views/instances/_details.html.haml
> +          - t.add_row({th: t("collections.id")}, {td: link_to_with_actions(@instance["@id"], acronym: @ontology.acronym) })
change "collections.id" with "instances.id"

2024-06-21 08:46 UTC, syphax-bouazzouni commented on config/routes.rb
> +  get 'mappings/ontology_mappings/:acronym', to: 'mappings#ontology_mappings'
to remove

2024-06-21 08:46 UTC, syphax-bouazzouni commented on config/routes.rb
> +  get '/mappings_ontologies_table', to: 'mappings#mappings_ontologies_table'
to remove

2024-06-21 09:13 UTC, Bilelkihal reviewed
✅

2024-06-21 11:27 UTC, merged