Fix: Hide affiliations when agent is organization in agent form
ontoportal-lirmm/bioportal_web_ui pull request #696
Opened 2024-07-02 13:16 UTC by Bilelkihal

Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/589

2024-07-02 13:16 UTC, Bilelkihal reviewed
✅

2024-07-02 15:27 UTC, syphax-bouazzouni requested changes
Tests don't pass

2024-07-24 09:02 UTC, Bilelkihal commented
> Tests don't pass

Not related to this PR

2024-07-24 09:39 UTC, syphax-bouazzouni commented
> > Tests don't pass
> 
> Not related to this PR

This one is related to this PR

![image](https://github.com/user-attachments/assets/47606cb7-6568-446c-ac43-605f8a7a3b02)

2024-07-30 17:54 UTC, syphax-bouazzouni requested changes

2024-07-30 17:54 UTC, syphax-bouazzouni commented on test/system/submission_flows_test.rb
Still, the test don't pass
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/e22bc081-e7bf-46f7-95d8-fd9a1408718c">

2024-08-04 07:54 UTC, syphax-bouazzouni approved these changes
Code approved and fixed the remaining tests in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/696/commits/667f8b0917bf5cfea09c95f32ffb787ccc9690b9

2024-08-04 07:54 UTC, merged