Feature: Select children of category when selecting it
ontoportal-lirmm/bioportal_web_ui pull request #773
Opened 2024-10-10 17:45 UTC by Bilelkihal

2024-10-10 18:15 UTC, Bilelkihal commented on app/javascript/controllers/categories_controller.js
> +    #nest_children_inside_parents(){
I did a mistake,
when I select a category I should select the parent of it, but when I deselect the parent I should deselect the children also

2024-10-11 10:12 UTC, Bilelkihal commented
@syphax-bouazzouni
This PR is based on the branch from PR [#772](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/772). Once that PR is merged, the number of files in this PR will be reduced.

2024-10-11 12:59 UTC, jonquet commented
C'est super bravo.

2024-10-11 13:51 UTC, syphax-bouazzouni requested changes

2024-10-11 13:51 UTC, syphax-bouazzouni commented on app/javascript/controllers/categories_controller.js
> +// Connects to data-controller="categories"
this file need be called `parent_catregories_selector`

2024-11-01 19:48 UTC, syphax-bouazzouni requested changes
Need to resolve the conflicts and do the old changes request

2024-11-07 15:00 UTC, Bilelkihal commented
@syphax-bouazzouni I added it to the upload and edit ontology forms, 
and resolved all the conflicts with the federation categories refresh code.

Ready to be merged now.

2024-11-28 13:54 UTC, syphax-bouazzouni commented
@Bilelkihal what is the state of this? will it be abandoned or adapted or is it already good to be merged?
If abandoned you can close it. 
If need to be adapted transform it into a draft.
If ready to be merged I will do the review.

2024-12-01 08:37 UTC, jonquet commented
To my knowledge we were waiting for the federation to be activated and the new features related to categories assessed before enabling this.

2025-01-02 15:24 UTC, Bilelkihal commented
@syphax-bouazzouni Ready for review

2025-01-02 18:23 UTC, syphax-bouazzouni requested changes

2025-01-02 18:23 UTC, syphax-bouazzouni commented on app/helpers/submission_inputs_helper.rb
> +      content_tag(:div, class: 'upload-ontology-chips-container', 'data-controller': 'parent-categories-selector', 'data-parent-categories-selector-categories-value': "#{categories.to_json}", 'data-p
why do you pass here `"#{categories.to_json}"`, in the code you need only the children categories of the clicked chip category. 

Said otherwise move the logic from the controller js to Ruby

2025-01-03 10:02 UTC, Bilelkihal commented on app/helpers/submission_inputs_helper.rb
> +      content_tag(:div, class: 'upload-ontology-chips-container', 'data-controller': 'parent-categories-selector', 'data-parent-categories-selector-categories-value': "#{categories.to_json}", 'data-p
Done, but also the logic of categories is changed since the time I created this PR, so I need to adapt it to the changes done before merging

2025-01-03 10:08 UTC, syphax-bouazzouni requested changes

2025-01-03 10:08 UTC, syphax-bouazzouni commented on app/helpers/application_helper.rb
> +  def id_to_acronym(id)
already exist 
![image](https://github.com/user-attachments/assets/5bd3f0f6-652f-424c-ab48-6017dc7043c9)

2025-01-03 10:08 UTC, syphax-bouazzouni commented on app/helpers/submission_inputs_helper.rb
> +      content_tag(:div, class: 'upload-ontology-chips-container', 'data-controller': 'parent-categories-selector', 'data-parent-categories-selector-categories-children-value': "#{categories_children.
Here you should pass, only the children of the current category chips, or empty if it does not have children.
Like that, the stimulus controller will just read that value (array) and select or deselect.

2025-01-03 10:36 UTC, Bilelkihal commented on app/helpers/submission_inputs_helper.rb
> +      content_tag(:div, class: 'upload-ontology-chips-container', 'data-controller': 'parent-categories-selector', 'data-parent-categories-selector-categories-children-value': "#{categories_children.
We are not in the level of a single category here but all categories

2025-01-03 10:37 UTC, Bilelkihal commented
@syphax-bouazzouni This PR is ready to be merged

2025-01-03 11:19 UTC, syphax-bouazzouni commented on app/helpers/submission_inputs_helper.rb
> +      content_tag(:div, class: 'upload-ontology-chips-container', 'data-controller': 'parent-categories-selector', 'data-parent-categories-selector-categories-children-value': "#{categories_children.
ah yes,

2025-01-03 11:20 UTC, syphax-bouazzouni approved these changes

2025-01-03 11:21 UTC, merged

2025-01-03 14:54 UTC, Bilelkihal commented
We did a mistake here:
The logic of selecting categories in upload and edit form need to be inversed comparing to the one of the browse page,
in the browse page:
selecting a parent should select the children

but in the attribution of categories in upload or edit forms:
selecting a child should select the parents of it