Feature: Add enable/disable federation
ontoportal-lirmm/bioportal_web_ui pull request #780
Opened 2024-10-24 09:32 UTC by Bilelkihal

### Changes
- Check if there's in the config file a portal that has an api and an api_key, if no one is found then we set the federation to disabled.
- If the federation is disabled then we don't display the federation inputs in search and browser pages

2024-10-24 09:35 UTC, Bilelkihal reviewed
✅

2024-10-24 09:37 UTC, syphax-bouazzouni requested changes
See comments, and maybe need to check also the home page, if we need to disable some parts.

2024-10-24 09:37 UTC, syphax-bouazzouni commented on app/helpers/federation_helper.rb
> +  def federation_portals_enabled?
rename to `federated_request?` as it relates to the current request state, to check if it is federated or not.

2024-10-24 09:37 UTC, syphax-bouazzouni commented on app/controllers/concerns/search_aggregator.rb
> +      search_results = merge_sort_federated_results(query, search_results) if federation_portals_enabled?
no need of this second check here,

2024-10-24 09:37 UTC, syphax-bouazzouni commented on app/controllers/ontologies_controller.rb
> +    @federation_enabled = federation_enabled?
no need to put it here, directly call the helper in the view

2024-10-24 09:37 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +    @federation_enabled = federation_enabled?
no need to put it here, directly call the helper in the view

2024-10-26 07:59 UTC, syphax-bouazzouni commented on app/helpers/federation_helper.rb
> +  def federation_portals_enabled?
Done https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/780/commits/745b0e13120a2cf0dcfb5e274ea5c9d0621788ca

2024-10-26 08:00 UTC, syphax-bouazzouni commented on app/controllers/ontologies_controller.rb
> +    @federation_enabled = federation_enabled?
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/780/commits/ab9f5b4e1d42adc165bbf5a92bf9dd49e102bf35

2024-10-26 08:00 UTC, syphax-bouazzouni commented on app/controllers/search_controller.rb
> +    @federation_enabled = federation_enabled?
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/780/commits/ab9f5b4e1d42adc165bbf5a92bf9dd49e102bf35

2024-10-26 08:00 UTC, syphax-bouazzouni commented on app/controllers/concerns/search_aggregator.rb
> +      search_results = merge_sort_federated_results(query, search_results) if federation_portals_enabled?
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/780/commits/ab9f5b4e1d42adc165bbf5a92bf9dd49e102bf35

2024-10-26 08:13 UTC, syphax-bouazzouni commented
Did some proposed refactoring and fixed a bug of bad routes for the federation status in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/780/commits/5c24d894752957cfd3c08235b8b6bb35d8eb0612, where it goes to `/ontologies/status` instead of the correct route `/status`

2024-10-26 08:13 UTC, syphax-bouazzouni approved these changes

2024-10-26 08:31 UTC, merged