Fix: Search federation duplicated results merging issue
ontoportal-lirmm/bioportal_web_ui pull request #830
Opened 2024-11-06 10:07 UTC by Bilelkihal

Fixed issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/829

### Changes
The previous logic to detect duplicate search results combined the concept URI and ontology acronym. However, it attempted to retrieve the ontology acronym using `element[:root][:ontology_acronym]`, which doesn’t exist as a key under `element[:root]`. Instead, only the ontology ID is available in this structure.

To resolve this:

- Extracted the ontology acronym from the available ontology ID.
- Replaced the previous key lookup with this derived acronym to ensure proper duplicate detection.

### Screenshot
![image](https://github.com/user-attachments/assets/212f33f5-f2a5-43d8-bf97-276bb1497999)

2024-11-06 10:07 UTC, Bilelkihal commented on app/controllers/concerns/search_aggregator.rb
> +        if (element[:root][:ontology_id].split('/').last == reuse[:root][:ontology_id].split('/').last) && (element[:root][:uri] == reuse[:root][:uri])
put this in a variable to make it lisible

2024-11-06 14:25 UTC, syphax-bouazzouni requested changes

2024-11-06 14:25 UTC, syphax-bouazzouni commented on app/controllers/concerns/search_aggregator.rb
> -            ontology_id: reuse[:root][:ontology_id]
why not just add `ontology_aconym` here?

2024-11-06 14:25 UTC, syphax-bouazzouni commented on app/controllers/concerns/search_aggregator.rb
> -            ontology_id: reuse[:root][:ontology_id]
and in line 91?

2024-11-07 04:32 UTC, syphax-bouazzouni commented on app/controllers/concerns/search_aggregator.rb
> -            ontology_id: reuse[:root][:ontology_id]
Ok I got you.

2024-11-07 04:32 UTC, syphax-bouazzouni approved these changes

2024-11-07 04:32 UTC, merged