Fix: Improve taxonomy page, fix static portal name, detect description link
ontoportal-lirmm/bioportal_web_ui pull request #850
Opened 2024-11-12 17:11 UTC by Bilelkihal

Fix: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/788

### Changes
- Detect if the taxonomy description is a link and handle that (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/b961561ddc8d528c28f2d9eff7dbcc8d1bebd289)
<img width="1712" alt="image" src="https://github.com/user-attachments/assets/9f459d5f-37ca-4844-be4d-8e596c208f13">

If it's not a link we keep the default behavior
<img width="1712" alt="image" src="https://github.com/user-attachments/assets/c43a44f0-2187-4d22-a7c2-51de71500d3a">

- Make portal name dynamic in taxonomy page description (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/7c432791635c61154fa826d42d32974fcb623483)

- Retouch taxonomy page description to replace "In 2024, we moved to UNESCO nomenclature for fields of science and technology" by "In 2024, we moved to UNESCO Thesaurus (https://vocabularies.unesco.org/)." (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/2606cbe04a246218d6b35d1f0a56783a2791874f)

2024-11-12 17:13 UTC, Bilelkihal reviewed
✅

2024-11-13 15:43 UTC, syphax-bouazzouni requested changes

2024-11-13 15:43 UTC, syphax-bouazzouni commented on app/components/display/taxonomy_card_component.rb
> +    uri_regex = URI::DEFAULT_PARSER.make_regexp
you use existebt helper called `link?(str)` which defined in urls_helper.rb

2024-11-18 15:27 UTC, syphax-bouazzouni approved these changes

2024-11-18 15:53 UTC, merged