Fix: Taxonomy empty list
ontoportal-lirmm/bioportal_web_ui pull request #858
Opened 2024-11-21 09:00 UTC by Bilelkihal

2024-11-21 09:06 UTC, Bilelkihal commented on app/views/taxonomy/_taxonomies.html.haml
> +                No group is created yet
To be internationalized

2024-11-21 09:06 UTC, Bilelkihal commented on app/views/taxonomy/_taxonomies.html.haml
> +                    = render Buttons::RegularButtonComponent.new(id:'create-taxonomy', value: "Create #{type}", variant: "secondary", size: "slim", href: "/admin?section=#{type}")
To be internatinalized

2024-11-21 10:31 UTC, syphax-bouazzouni requested changes
Some change requests and the tests seems to not pass

2024-11-21 10:31 UTC, syphax-bouazzouni commented on app/views/taxonomy/_taxonomies.html.haml
> +                No group is created yet
use empty_state helper here

2024-11-21 10:31 UTC, syphax-bouazzouni commented on app/views/taxonomy/_taxonomies.html.haml
> +            - if session[:user]&.admin?
use` current_user_admin?` helper

2024-11-21 10:31 UTC, syphax-bouazzouni commented on app/views/taxonomy/_taxonomies.html.haml
> +                    = render Buttons::RegularButtonComponent.new(id:'create-taxonomy', value: "Create #{type}", variant: "secondary", size: "slim", href: "/admin?section=#{type}")
use `regular_button` helper, will be cleaner than render Buttons::RegularButtonComponent.new(...)

2024-11-25 20:58 UTC, Bilelkihal commented
Deployed to stage

2024-11-26 10:20 UTC, merged