Feature/add metadata curator
ontoportal-lirmm/bioportal_web_ui pull request #87
Opened 2022-07-08 10:06 UTC by bouchnam

bootstrap for the metadata table and the pop up modal for editing the metadata

2022-07-11 08:13 UTC, syphax-bouazzouni requested changes
Need to do some changes

2022-07-11 12:40 UTC, bouchnam commented on app/views/ontologies_metadata/_form.html.haml
> +%div{:style => "padding:10px"}
It's actually used in the form_edit file , with a render, just to separate things so we can use this form in more files if needed

2022-07-20 15:29 UTC, syphax-bouazzouni requested changes

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +            @ontologies << LinkedData::Client::Models::Ontology.all.detect {|e| e.acronym == data}
Not optimized code.

You call  `LinkedData::Client::Models::Ontology.all` inside your for each loop, which means if you have 10 ontologies_ids you will fetch all the ontologies each time.

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +            @submissions << LinkedData::Client::Models::OntologySubmission.all.detect {|e| e.ontology.acronym == data}
Even worst here

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +            @ontologies = LinkedData::Client::Models::Ontology.all.sort_by {|e| e.name}
don't call `LinkedData::Client::Models::Ontology.all` each time same it inside a variable.

`LinkedData::Client::Models::Ontology.all` will call each time the data base for the same thing

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +            @submissions = LinkedData::Client::Models::OntologySubmission.all.sort_by {|e| e.ontology.name}
same

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +            format.turbo_stream { render turbo_stream: turbo_stream.append("choices", partial: "ontologies_metadata_curator/result") }
replace the frame name "choices", with something more specific that has a meaning.

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +        # @selected_ontologies_edit = @ontologies.where(acronym: params[:ontologies_acronymes])
remove comments

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +        @submission = LinkedData::Client::Models::OntologySubmission.all.detect {|e| e.ontology.acronym == @ontology[0].acronym}
you can directly do in the place of `@submission = LinkedData::Client::Models::OntologySubmission.all.detect {|e| e.ontology.acronym == @ontology[0].acronym}` something like so `@submission =  @ontology.explore.latest_submission`

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/controllers/ontologies_metadata_curator_controller.rb
> +            format.turbo_stream { render turbo_stream: turbo_stream.replace("editmodal", partial: "ontologies_metadata_curator/form_edit") }
find a better name that "editmodal"

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/views/admin/index.html.haml
> +        -#= turbo_frame_tag "metadata"
remove `-#= turbo_frame_tag "metadata" `if it's just a comment

2022-07-20 15:29 UTC, syphax-bouazzouni commented on app/views/ontologies_metadata_curator/_result.html.haml
> += turbo_frame_tag "metadata" do
choose a better name than "metadata"

2022-11-25 16:50 UTC, syphax-bouazzouni commented
Suite possible http://dashboard.obofoundry.org/dashboard/index.html

2022-12-08 12:50 UTC, merged