Fix: Prevent delete category if still used as parent category
ontoportal-lirmm/bioportal_web_ui pull request #876
Opened 2024-11-28 09:28 UTC by Bilelkihal

### Changes
- Prevent delete category if still used as parent category (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/357a86ecd3db857baacf89f18a22a585bf19de20)

2024-11-28 09:29 UTC, Bilelkihal commented on app/views/admin/categories/_category.html.haml
> +  - parent_error_message = "Can't delete category, used as a parent category for: "
text need to be internationalized

2024-11-28 13:52 UTC, syphax-bouazzouni requested changes

2024-11-28 13:52 UTC, syphax-bouazzouni commented on app/views/admin/categories/_category.html.haml
> +  - is_parent = @parents_list.keys.include?(category.id)
this logic need to be in helpers

2024-12-10 22:02 UTC, syphax-bouazzouni approved these changes

2024-12-10 22:02 UTC, merged